name: SQL Runner

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment (dev, qa, prod)'
        required: true
        type: string
      file:
        description: 'SQL file to run (optional, leave blank to list files)'
        required: false
        type: string

jobs:
  sql-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set variables
        run: |
          echo "ENV=${{ github.event.inputs.env }}" >> $GITHUB_ENV
          echo "FILE=${{ github.event.inputs.file }}" >> $GITHUB_ENV

      - name: List SQL files (if no file selected)
        if: env.FILE == ''
        run: |
          echo "Listing SQL files in sql/$ENV/:"
          FILES=$(ls sql/$ENV/*.sql || echo "No files found")
          echo "$FILES"
          # Post as comment
          gh auth setup-git
          gh api repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments \
            -f body="Available SQL files for environment $ENV:\n$FILES"

      - name: Run SQL file (if file selected)
        if: env.FILE != ''
        run: |
          SQL_PATH="sql/$ENV/$FILE"
          if [ ! -f "$SQL_PATH" ]; then
            echo "Error: $SQL_PATH not found"
            exit 1
          fi
          echo "Running SQL file: $SQL_PATH"
          # Replace with your DB command
          echo "Simulating execution of $SQL_PATH"
